### ISSUE TITLE
间隔太久

### ISSUE THREAD

**Issue by liqilei** [hack-fan/skadi-agent-shell#3]
你好，感觉给公众号发指令之后，等待时间太久，而且两次指令中间的等待时间也很久，请问有办法调整吗？

**Comment by hyacinthus** [comment]
默认时间确实有点久，下个版本会缩短这个时间并让其在配置中可调。

**Comment by liqilei** [comment]
感谢您的回复。
很好的一个软件，使用得到可以作为远程的terminal执行任何的操作，非常方便管理server。

**Comment by hyacinthus** [comment]
最新版本已经把检查时间从60秒调整到10秒。

开源版本不准备将间隔调的更小或支持长链接。将来如果有需求的人多可能在Pro版本中实现。

**Comment by liqilei** [comment]
请问我应该如何更新到最新版本呢？

**Comment by hyacinthus** [comment]
> 请问我应该如何更新到最新版本呢？

就用系统更新就行了

比如debian是

```bash
apt update
apt upgrade skadi
# 看看重启了没
systemctl status skadi
# 没有的话
systemctl restart skadi
```
