### ISSUE TITLE
公众号返回部分内容

### ISSUE THREAD

**Issue by liqilei** [hack-fan/skadi-agent-shell#4]
你好，使用指令后，公众号返回只有部分内容（实际内容的前部分），请问是否有办法返回更多，或者将内容分段返回呢？

**Comment by hyacinthus** [comment]
微信消息有长度限制。未来会在缩略后提供一个网页让点击看到全部内容，但暂时还没有时间表，最近有时间了会改善一下。

**Comment by liqilei** [comment]
感谢您的回复。听起来就很炫酷！期待
