### ISSUE TITLE
请问可以增加arm处理器的版本吗

### ISSUE THREAD

**Issue by HNQX** [hack-fan/skadi-agent-shell#6]
我在nanoPI上运行不了/skadi，下载的是skadi-agent-shell_1.2.2_Linux_x86_64.tar.gz
![PI](https://cdn.jsdelivr.net/gh/HNQX/img/skadi.png)
万分感谢！

**Comment by hyacinthus** [comment]
理论上应该可以 过两天我加一下

**Comment by HNQX** [comment]
> 理论上应该可以 过两天我加一下

谢谢

**Comment by hyacinthus** [comment]
编译了arm64的版本，试试。

**Comment by HNQX** [comment]
> 

可以用啦，感谢！
![started](https://cdn.jsdelivr.net/gh/HNQX/img/issue/skadi_started.png)
